services:
  solana-dev:
    build: .
    container_name: solana-dev
    stdin_open: true
    tty: true
    user: "1000:1000"
    working_dir: /home/ubuntu/workspace
    volumes:
      - ./workspace:/home/ubuntu/workspace
    deploy:
      resources:
        limits:
          cpus: '6.00'
          memory: 8g
    environment:
      - CARGO_TERM_COLOR=always
    network_mode: host
